# Generated by Django 5.0.6 on 2024-06-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_date_create_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите новую запись",
                        max_length=100,
                        verbose_name="Запись",
                    ),
                ),
                (
                    "slug",
                    models.CharField(
                        db_index=True, max_length=150, unique=True, verbose_name="URL"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=100, verbose_name="Описание"),
                ),
                (
                    "photo",
                    models.ImageField(
                        help_text="Загрузите новое фото",
                        upload_to="product/photo",
                        verbose_name="Фото",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату загрузки",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "views_counter",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Укажите количество просмотров",
                        verbose_name="Счетчик просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "Блог",
                "verbose_name_plural": "Блоги",
                "ordering": ["name", "description"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Укажите количество просмотров",
                verbose_name="Счетчик просмотров",
            ),
        ),
    ]
