# Generated by Django 5.0.6 on 2024-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_blognote_product_views_counter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Version",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.CharField(
                        help_text="Введите новый продукт",
                        max_length=100,
                        verbose_name="продукт",
                    ),
                ),
                (
                    "version_number",
                    models.PositiveIntegerField(default=0, verbose_name="номер версии"),
                ),
                (
                    "version_name",
                    models.CharField(max_length=100, verbose_name="номер версии"),
                ),
            ],
            options={
                "verbose_name": "Версия",
                "verbose_name_plural": "Версии",
                "ordering": ["product"],
            },
        ),
    ]
