# Generated by Django 5.0.6 on 2024-07-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="blognote",
            name="publication_status",
            field=models.BooleanField(default=False),
        ),
    ]
